name: regular-release
"on":
  push:
    branches:
    - main
permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write
env:
  AWS_REGION: eu-west-1

jobs:
  regular-release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com/'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Release the project
      run: npm run release
